on:
  workflow_dispatch: {}
  push:
    branches:
      - main  # Trigger on commits to the main branch
    paths:
      - .github/workflows/semgrep.yml  # Optional: specify paths to limit trigger to changes in this file

name: Semgrep
jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@v4
      - run: semgrep ci
